version: "2"
services:
  postgres:
    build: ./db
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: postgres

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: claire
      RABBITMQ_DEFAULT_USER: claire
    image: "rabbitmq:3.6.10"

  redis:
    environment:
      REDIS_DEFAULT_PASS: claire
      REDIS_DEFAULT_USER: claire
    image: "redis:alpine"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
    # environment:
    #   - 'transport.host=0.0.0.0'
    #   - 'network.host=0.0.0.0'
    ports:
      - 9200:9200
      - 9300:9300
    logging:
      driver: none

  service:
    container_name: clairvoyance_service_ml
    build: .
    depends_on:
      - postgres
      - redis
      - elastic
    ports:
      - "8080:3000"
    volumes:
      - "./:/app"
    entrypoint: ["tail", "-f", "/dev/null"]
